export const GET_TRS_INFO = 'GET_TRS_INFO';
export const GET_TRS_INFO_SUCCESS = 'GET_TRS_INFO_SUCCESS';
export const GET_TRS_INFO_FAILED = 'GET_TRS_INFO_FAILED';

export const GET_REBUS_INFO = 'GET_REBUS_INFO';
export const GET_REBUS_INFO_SUCCESS = 'GET_REBUS_INFO_SUCCESS';
export const GET_REBUS_INFO_FAILED = 'GET_REBUS_INFO_FAILED';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const GET_TRS_GLOBALE_INFO = 'GET_TRS_GLOBALE_INFO';
export const GET_TRS_GLOBALE_INFO_SUCCESS = 'GET_TRS_GLOBALE_INFO_SUCCESS';
export const GET_TRS_GLOBALE_INFO_FAILED = 'GET_TRS_GLOBALE_INFO_FAILED';

export const GET_ABSENT_INFO = 'GET_ABSENT_INFO';
export const GET_ABSENT_INFO_SUCCESS = 'GET_ABSENT_INFO_SUCCESS';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';

export const ADD_NEW_QRQC = 'ADD_NEW_QRQC';
export const ADD_NEW_QRQC_SUCCESS = 'ADD_NEW_QRQC_SUCCESS';
export const GET_QRQC_LIST = 'GET_QRQC_LIST';
export const GET_QRQC_LIST_SUCCESS = 'GET_QRQC_LIST_SUCCESS';

export const GET_TEMPS_EFFICIENT = 'GET_TEMPS_EFFICIENT';
export const GET_TEMPS_EFFICIENT_SUCCESS = 'GET_TEMPS_EFFICIENT_SUCCESS';

export const GET_OTD_INFO = 'GET_OTD_INFO';
export const GET_OTD_INFO_SUCCESS = 'GET_OTD_INFO_SUCCESS';

export const GET_AUDIT_LIST = 'GET_AUDIT_LIST';
export const GET_AUDIT_LIST_SUCCESS = 'GET_AUDIT_LIST_SUCCESS';
export const ADD_AUDIT_TASK = 'ADD_AUDIT_TASK';
export const ADD_AUDIT_TASK_SUCCESS = 'ADD_AUDIT_TASK_SUCCESS';
export const GET_AUDIT_DETAILS_ACTION = 'GET_AUDIT_DETAILS_ACTION';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const ADD_ALERT = 'ADD_ALERT';
export const GET_ALL_ALERTS = 'GET_ALL_ALERTS';
export const GET_ALL_ALERTS_SUCCESS = 'GET_ALL_ALERTS_SUCCESS';
export const GET_ALL_ALERTS_SENDED_SUCCESS = 'GET_ALL_ALERTS_SENDED_SUCCESS';
export const SELECTED_AUDIT_TO_EDIT = 'SELECTED_AUDIT_TO_EDIT';
export const EDIT_USER_INFO = 'EDIT_USER_INFO';

export const ADD_OBJECTIF = 'ADD_OBJECTIF';
export const UPDATE_OBJECTIF = 'UPDATE_OBJECTIF';
export const DELETE_OBJECTIF = 'DELETE_OBJECTIF';
export const GET_ALL_OBJECTIF = 'GET_ALL_OBJECTIF';
